### ISSUE TITLE
Add documentation re: wdl compile applet reuse

### ISSUE THREAD

**Issue by odoublewen** [dnanexus/dxWDL#239]
I was rather pleased to discover that when recompiling a workflow, tasks that were unchanged do not get built as new applets.  So dxWDL's applet reuse allows DNAnexus job reuse to work!  😃 🎆 🍾  

It would be really helpful to have explicit documentation for how dxWDL "knows" that an applet does not need to be rebuilt.  What exactly is happening under the hood?  From the discussion in #154 it sounds like the task closure is hashed -- is that just a textual hash?  Would adding `#comments` to a task trigger a rebuild?  If the task closure doesn't change but the docker image it refers to has changed, would dxWDL pick that up?   We currently stash~ing~ our internally developed docker images on DNAnexus, so there is no enforcement of version tags, so we could in theory update a docker image to get some new behavior without changing the WDL task -- not saying this would be a good plan, just tying to understand exactly how applet reuse works.

Does this documentation exist -- am I just overlooking it?

**Comment by orodeh** [comment]
I am glad you are getting good mileage out of job reuse :-)

This isn't documented, and certainly should be. The inline answer below discusses tasks, but the same holds for workflows.

If you modify the task source code, even adding comments, the corresponding applet will be recompiled. The older compiler optimized this, it disregarded comments and white space, but I am not going through the trouble any more. I *think* it isn't worth it, it may actually be confusing. 

The JSON request to DNAnexus for creating the applet is serialized and check-summed. If any argument to this request has been modified, the applet will be rebuilt. Because the docker image is on the platform, it is immutable, and its ID will change when you modify it. This will cause the applet to be rebuilt. 

Very few things are not under checksum protection. A notible exception is properties, these can be modified later by hand, and will not caused recompilation.

**Comment by odoublewen** [comment]
Thanks for the clarifications.  One more point I'd like to double check:

> Because the docker image is on the platform, it is immutable, and its ID will change when you modify it. This will cause the applet to be rebuilt.

This is true even if we're referring to the image in the WDL workflow by its name and not ID?  

i.e.:
```
  runtime {
    docker: "dx://myimages:/my_app_image"
  }
```

I guess I can check this empirically........ yes it seems to be the case that the task hash is made after looking up the container's ID.  Furthermore, it appears that the task is recompiled if the docker filename changes even if the underlying ID is unchanged.

So, changing either the docker filename (with object unchanged) or changing the docker file object (withe the filename unchanged) -- either of these cases appear to trigger a recompile.

That's all fine, just want to be sure I explicitly understand what's happening.  (Trying to work out best practices for naming docker objects stored in DNAnexus.)

**Comment by orodeh** [comment]
Docker image naming is an important point. At compile time, the docker path (`dx://myimages:/my_app_image`) is resolved, and a reference of the kind `project-id:object-id` replaces it. This allows writing full paths in WDL source file, making them more readable.

I might be missing something here. If you change the docker file name, then you have to change the source WDL file, no? In that case, the source change will cause recompilation.

**Comment by odoublewen** [comment]
> If you change the docker file name, then you have to change the source WDL file, no? 

Yes, you and I are saying the same thing.  My comment above started as a question, but then I answered it myself.  I decided to post it because detail like this would be useful in the docs.  Thanks.

**Comment by orodeh** [comment]
Added a section to the documentation on master branch. 

https://github.com/dnanexus/dxWDL/blob/master/doc/ExpertOptions.md#recompilation
